### ISSUE TITLE
crypto:rand_bytes/1 not supported, use crypto:strong_rand_bytes/1

### ISSUE THREAD

**Issue by etxemag75** [RNCryptor/RNCryptor-erlang#1]
In newer OTP versions, crypto:rand_bytes/1 is removed.
Seems like crypto:strong_rand_bytes/1 could be used instead.

rncryptor.erl:  HmacKey = crypto:rand_bytes(?HMAC_SHA256_SIZE),
rncryptor.erl:      IVec = crypto:rand_bytes(?AES256_IVEC_SIZE),
rncryptor.erl:  IVec = crypto:rand_bytes(?AES256_IVEC_SIZE),
rncryptor_kdf.erl:  Salt = crypto:rand_bytes(?PBKDF2_DEFAULT_SALT_SIZE),

**Comment by dingosky** [comment]
Commit b2922a0 closes #1

**Comment by etxemag75** [comment]
I think this commit made it worse since crypto:crypto_one_time does not exists in Erlang/OTP 21 [erts-10.2] etc

=ERROR REPORT==== 20-Jun-2019::01:21:00.067928 ===
    exception: error
    reason: undef
    stack: [{crypto,crypto_one_time,
                    [aes_256_cbc,
                     <<157,85,115,255,89,237,153,173,2,155,44,254,21,205,180,
                       255,214,73,55,51,235,2,77,244,11,48,202,240,185,1,4,136>>,
                     <<191,91,242,16,201,248,188,242,172,56,39,162,140,198,202,
                       162>>,
                     <<40,117,198,88,149,164,67,63,112,232,128,249,106,134,169,
                       173>>,
                     false],
                    []},
            {rncryptor,decrypt_pw,2,
                       [{file,"/Users/test/deps/rncryptor/src/rncryptor.erl"},
                        {line,297}]},

**Comment by dingosky** [comment]
Commit b2822a0 should have been two separate commits, the first to fix the Cipher IV issue and the second to use the new crypto API.

There is a new branch, otp_21, that includes the fix for Cipher IV without using the new crypto API. It is tagged as 3.0.1_otp_21. Using either the branch or tag to pull that version will fix the original issue (use of crypto:rand_bytes).
